apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: app-config
    literals:
      - GREETING_PREFIX=hello
generatorOptions:
  disableNameSuffixHash: true
