name: CI/CD Pipeline - Quarkus

on:
    push:
        branches:
            - main

jobs:
    build-test-package:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: install maven
              run: sudo apt-get update && sudo apt-get install -y maven

            - name: build & test with Maven
              run: mvn clean verify -DskipTests=false

            - name: package application
              run: mvn package -DskipTests=true

            - name: generate image tag
              id: vars
              run: echo "tag=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

            - name: build container image
              run: |
                  docker build \
                    --build-arg JAR_FILE=target/*-runner.jar \
                    -t quarkus-app:${{ env.tag }} \
                    -t quarkus-app:latest .

            - name: check minikube
              run: |
                  minikube status
                  kubectl get pods -A

            - name: load image into minikube
              run: |
                  minikube image load quarkus-app:${{ env.tag }}

    deploy:
        runs-on: ubuntu-latest
        needs: build-test-package
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: deploy to des namespace
              run: |
                  kubectl create namespace des --dry-run=client -o yaml | kubectl apply -f -
                  kubectl -n des apply -f k8s/deployment.yaml
                  kubectl -n des rollout status deployment/quarkus-app

            - name: deploy to prd namespace if des OK
              run: |
                  kubectl create namespace prd --dry-run=client -o yaml | kubectl apply -f -
                  kubectl -n prd apply -f k8s/deployment.yaml
                  kubectl -n prd rollout status deployment/quarkus-app
